apiVersion: apps/v1
kind: Deployment
metadata:
  name: identity-deployment
spec:
  selector:
    matchLabels:
      app: identity
  template:
    metadata:
      labels:
        # must match app from matchLabels above
        app: identity
    spec:
      containers:
      # this name here has nothing to do with the container
      - name: identity
        image: playeconomycontainerregistry.azurecr.io/play.identity:1.0.5
        env:
          - name: ServiceSettings__MessageBroker
            value: SERVICEBUS 
        resources:
          limits:
            memory: "128Mi"
            cpu: "150m"
        ports:
        - containerPort: 5002


